"""empty message

Revision ID: a25d2de3faf1
Revises: 25ccabcab051
Create Date: 2020-04-24 19:55:41.165672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25d2de3faf1'
down_revision = '25ccabcab051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_artist', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_artist_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_artist_description')
    op.drop_column('Venue', 'seeking_artist')
    op.drop_column('Artist', 'seeking_venue_description')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
